### ISSUE TITLE
Documentation / Getting Started

### ISSUE THREAD

**Issue by OranguTech** [dsccommunity/JeaDsc#44]
Readme is unchanged from the MS-official repo. This is the only JEA DSC resource on powershell gallery, and it's been updated recently, so that's what I'm attempting to use. Where's the official "JustEnoughAdministration" module? How stable/used is this one? Etc.

**Comment by malthe** [comment]
Also, is this repository maintained – ?

See for example #48 which looks trivial and is currently 8 months old.

**Comment by gaelcolas** [comment]
It is maintained, but we've got too many noise from github to keep track.
Best is to come and shout on [aka.ms/PSDiscord](https://aka.ms/PSDiscord) in the DSC Channel.

**Comment by gaelcolas** [comment]
#48 has been closed, fwiw
